use_frameworks!

platform :ios, '12.0'

target 'CFAScan_Example' do
  pod  'PPBlinkID', '~> 5.4.0'
  pod 'CFAScan', :path => '../'

  target 'CFAScan_Tests' do
    inherit! :search_paths

    
  end
end
